#!/bin/bash

:<<'END'

 read a
 cd /home/cases/Documents/Master1/ProgWeb/projet$a/
 pwd
 ls

END

#for AA
#cd /amuhome/c14014169/

for LINE in [[ awk '/[0-9]$/ { print }' 2 ]],
	do
		(( cat 2 | sed "/$LINE/" ))
	done
 


function blah(){
 read a;
 cd /home/cases/Documents/Master1/ProgWeb/projet$a/;
 pwd;
};

blah()





# b="$( pwd )"
